apiVersion: v1
kind: Namespace
metadata:
  name: bootstrap
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bootstrap-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: bootstrap
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: istio-installer
  namespace: bootstrap
spec:
  restartPolicy: Never
  containers:
  - name: installer
    image: gcr.io/dummy/istio-installer:latest
    imagePullPolicy: Never
